### ISSUE TITLE
miss "EC_dQdV" define in Figure4_mac.m

### ISSUE THREAD

**Issue by Zhaolooloo** [rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation#16]
Thanks for sharing the calculation for dQdV and dVdQ, it's helpful~ 
But here is no "EC_dQdV" define for the call in the line 94 in the file Figure4_mac.m, the same with "EC_dVdQ".

**Comment by petermattia** [comment]
Fixed

**Comment by Zhaolooloo** [comment]
Sorry for bothering you again, still missing "EC_dVdQ" function.

**Comment by petermattia** [comment]
thanks, fixed this time

**Comment by Zhaolooloo** [comment]
Thanks for sharing~~
